name: Release

on:
  push:
    tags: v*

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  build:
    permissions: write-all
    strategy:
      max-parallel: 1
      matrix:
        os: ["ubuntu", "windows"]

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
    - name: Install Snapcraft
      if: ${{ matrix.os == ubuntu }}
      run: sudo snap install snapcraft --classic
    - run: yarn install
    - run: yarn release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
